In [3]:
import numpy as np
data = np.array([1,2,3])
data[1]
data[0:2]
data[1:]
data[-2:]


array([2, 3])

In [5]:
import numpy as np
data = np.array([1,2,3])
data[1:]

array([2, 3])

In [4]:
import numpy as np
data = np.array([1,2,3])
data[0:2]

array([1, 2])

In [6]:
type(data[1:2])

numpy.ndarray

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(1)

array([1.])

In [9]:
np.empty(3)

array([0., 0., 0.])

In [10]:
np.empty(2)

array([-1.83509701e-31, -7.44195445e+35])

In [ ]:
np.ones()

In [11]:
ones=np.ones(shape=3,dtype=np.int8)

In [12]:
data

array([1, 2, 3])

In [13]:
data+ones+ones

array([3, 4, 5])

In [14]:
data-1

array([0, 1, 2])

In [15]:
data

array([1, 2, 3])

In [16]:
data*data

array([1, 4, 9])

In [17]:
data/data

array([1., 1., 1.])

In [18]:
data=np.array([1,2,3,4,5,6])

In [19]:
data.reshape(2,3)

ValueError: cannot reshape array of size 0 into shape (2,3)

In [20]:
data.reshape(2,3)

ValueError: cannot reshape array of size 0 into shape (2,3)

In [21]:
data=np.array([1,2,3,4,5,6])

In [22]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
r=[0][1]

IndexError: list index out of range

In [24]:
data=[0][1]

IndexError: list index out of range

In [25]:
r=data.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [26]:
r=data.reshape(2,3)

In [27]:
data

array([1, 2, 3, 4, 5, 6])

In [28]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
m=data.reshape(3,2)

In [30]:
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
m[0:1]

array([[1, 2]])

In [32]:
m[2:]

array([[5, 6]])

In [33]:
m.max()

6

In [34]:
m.min()

1

In [35]:
m.sum()

21

In [36]:
m.max(axis=0)

array([5, 6])

In [37]:
m.max(axis=1)

array([2, 4, 6])

In [38]:
m.min(axis=0)

array([1, 2])

In [39]:
m.min(axis=1)

array([1, 3, 5])

In [40]:
m.min(axis=0)

array([1, 2])

In [41]:
m.dim()

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [42]:
m.ndim()

TypeError: 'int' object is not callable

In [43]:
m.ndim

2

In [44]:
data.size

6

In [45]:
m.size

6

In [46]:
m.shape

(3, 2)

In [47]:
data.shape

(6,)

In [48]:
data=np.array([1,4,6,4,8])

In [51]:
d=data.sort(data)

TypeError: only integer scalar arrays can be converted to a scalar index

In [50]:
d

In [52]:
np.sort(data)

array([1, 4, 4, 6, 8])

In [53]:
np.concatenate((data,m))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [54]:
a=np.array([1,2,3])
b=np.array([2,4,5,6])

In [55]:
np.concatenate((a,b))

array([1, 2, 3, 2, 4, 5, 6])

In [56]:
np.unique(a)

array([1, 2, 3])

In [57]:
m.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [60]:
np.arange(100).reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [61]:
np.arange(start=1,stop=11,step=2)

array([1, 3, 5, 7, 9])

In [62]:
np.arrange

AttributeError: module 'numpy' has no attribute 'arrange'

In [63]:
np.arange(stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.linespace(1,10,num=5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [65]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])